@startuml

title __PROJECTILE's Class Diagram__\n

  namespace ro.uaic.info.game.objects.weapon {
    namespace projectile {
      class ro.uaic.info.game.objects.weapon.projectile.Projectile {
          - coordinates : Point
          - dimension : Rectangle
          - mesh : Rectangle
          + draw()
          + getCoordinates()
          + getDimension()
          + getMesh()
          + getProjectileType()
          + update()
      }
    }
  }
  

  namespace ro.uaic.info.game.objects.weapon {
    namespace projectile {
      enum ProjectileType {
      }
    }
  }
  

  ro.uaic.info.game.objects.weapon.projectile.Projectile o-- ro.uaic.info.game.objects.weapon.projectile.ProjectileType : projectileType


@enduml
