@startuml

title __SPACE's Class Diagram__\n

  namespace ro.uaic.info.engine {
    namespace space {
      class ro.uaic.info.engine.space.Double3 {
          - x : double
          - y : double
          - z : double
          + Double3()
          + Double3()
          + getX()
          + getY()
          + getZ()
          + setX()
          + setY()
          + setZ()
          + toString()
      }
    }
  }
  


@enduml
