@startuml

title __ENTITY's Class Diagram__\n

  namespace ro.uaic.info.engine {
    namespace entity {
      class ro.uaic.info.engine.entity.GameObjects {
          - gameObjects : List<GameObject>
          - gunAssets : List<Gun>
          - shipAssets : List<Ship>
          - triggers : List<Trigger>
          + GameObjects()
          + addGameObject()
          + addGameObjects()
          + addTrigger()
          + getAll()
          + getGun()
          + getPlayerObject()
          + getShip()
          + getTriggers()
          + redraw()
          + setPlayerObject()
          + toString()
          + update()
      }
    }
  }
  

  ro.uaic.info.engine.entity.GameObjects o-- ro.uaic.info.game.objects.player.Player : playerObject


@enduml
