@startuml

title __SHIP's Class Diagram__\n

  namespace ro.uaic.info.game.objects.ship {
    class ro.uaic.info.game.objects.ship.Ship {
        {static} - DEFAULT_SHIP_HEALTH : double
        - health : double
        - mesh : Shape
        - sprite : BufferedImage
        + Ship()
        + Ship()
        + Ship()
        + copy()
        + getHealth()
        + getSprite()
        + getTransform()
        + hasCollision()
        + hasMesh()
        + hasSprite()
        + setSprite()
        + setTransform()
        + toString()
    }
  }
  

  ro.uaic.info.game.objects.ship.Ship .up.|> ro.uaic.info.engine.object.GameObject
  ro.uaic.info.game.objects.ship.Ship o-- ro.uaic.info.engine.object.transform.Transform : transform

@enduml
